<center>
<img src="../../img/ods_stickers.jpg">
## Открытый курс по машинному обучению
<center>
Автор материала: Юрий Кашницкий, программист-исследователь Mail.Ru Group <br> 

Материал распространяется на условиях лицензии [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). Можно использовать в любых целях (редактировать, поправлять и брать за основу), кроме коммерческих, но с обязательным упоминанием автора материала.

In [5]:
!apt-get update
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

!mkdir -p drive
!google-drive-ocamlfuse drive

Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.

# <center>Домашнее задание № 1 (демо).<br> Анализ данных по доходу населения UCI Adult</center>

**В задании предлагается с помощью Pandas ответить на несколько вопросов по данным репозитория UCI [Adult](https://archive.ics.uci.edu/ml/datasets/Adult) (качать данные не надо – они уже есть в репозитории). Для отправки решений используйте [онлайн-форму](https://docs.google.com/forms/d/1xAzU-5N6oEeR4UG8G44V6XL-Kbr4WYcPBG45Kijge2Y).**

Уникальные значения признаков (больше информации по ссылке выше):
- age: continuous.
- workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- fnlwgt: continuous.
- education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- education-num: continuous.
- marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- sex: Female, Male.
- capital-gain: continuous.
- capital-loss: continuous.
- hours-per-week: continuous.
- native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- salary: >50K,<=50K

In [0]:
import pandas as pd

In [0]:
!ls drive/mlcourse/mlcourse_open-master/data/adult.data.csv

In [8]:
data = pd.read_csv('drive/mlcourse/mlcourse_open-master/data/adult.data.csv')
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Сколько мужчин и женщин (признак *sex*) представлено в этом наборе данных?**

In [138]:
data['sex'].value_counts()

Male      21790
Female    10771
Name: sex, dtype: int64

**2. Каков средний возраст (признак *age*) женщин?**

In [14]:
data[data['sex']=='Female']['age'].mean()

36.85823043357163

**3. Какова доля граждан Германии (признак *native-country*)?**

In [21]:
data['native-country'].value_counts(normalize=True)

United-States                 0.895857
Mexico                        0.019748
?                             0.017905
Philippines                   0.006081
Germany                       0.004207
Canada                        0.003716
Puerto-Rico                   0.003501
El-Salvador                   0.003255
India                         0.003071
Cuba                          0.002918
England                       0.002764
Jamaica                       0.002488
South                         0.002457
China                         0.002303
Italy                         0.002242
Dominican-Republic            0.002150
Vietnam                       0.002058
Guatemala                     0.001966
Japan                         0.001904
Poland                        0.001843
Columbia                      0.001812
Taiwan                        0.001566
Haiti                         0.001351
Iran                          0.001321
Portugal                      0.001136
Nicaragua                     0.001044
Peru                          0.000952
France                        0.000891
Greece                        0.000891
Ecuador                       0.000860
Ireland                       0.000737
Hong                          0.000614
Cambodia                      0.000584
Trinadad&Tobago               0.000584
Thailand                      0.000553
Laos                          0.000553
Yugoslavia                    0.000491
Outlying-US(Guam-USVI-etc)    0.000430
Hungary                       0.000399
Honduras                      0.000399
Scotland                      0.000369
Holand-Netherlands            0.000031
Name: native-country, dtype: float64

**4-5. Каковы средние значения и среднеквадратичные отклонения возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год? **

In [0]:
!ls

**6. Правда ли, что люди, которые получают больше 50k, имеют как минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [40]:
#data['sex'].count()
data[data['salary']=='>50K']['education']

7             HS-grad
8             Masters
9           Bachelors
10       Some-college
11          Bachelors
14          Assoc-voc
19            Masters
20          Doctorate
25          Bachelors
27       Some-college
38       Some-college
45          Bachelors
52        Prof-school
53          Bachelors
55       Some-college
63          Doctorate
67            HS-grad
68       Some-college
72          Bachelors
84            HS-grad
86            HS-grad
89          Doctorate
94          Bachelors
96          Doctorate
97       Some-college
100           Masters
101         Bachelors
105           HS-grad
111       Prof-school
112           HS-grad
             ...
32436     Prof-school
32438         Masters
32440    Some-college
32441    Some-college
32449         Masters
32453    Some-college
32455       Bachelors
32457         Masters
32458       Bachelors
32462         HS-grad
32464       Bachelors
32466     Prof-school
32474      Assoc-acdm
32480         Masters
32504         Masters
32506       Assoc-voc
32510         HS-grad
32513         Masters
32518         HS-grad
32519    Some-college
32530       Bachelors
32532       Doctorate
32533       Bachelors
32536       Bachelors
32538       Bachelors
32539       Doctorate
32545      Assoc-acdm
32554         Masters
32557         HS-grad
32560         HS-grad
Name: education, Length: 7841, dtype: object

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Amer-Indian-Eskimo*.**

In [49]:
data.groupby(['sex', 'race'])['age'].describe()

                             count       mean        std   min   25%   50%  \
sex    race
Female Amer-Indian-Eskimo    119.0  37.117647  13.114991  17.0  27.0  36.0
       Asian-Pac-Islander    346.0  35.089595  12.300845  17.0  25.0  33.0
       Black                1555.0  37.854019  12.637197  17.0  28.0  37.0
       Other                 109.0  31.678899  11.631599  17.0  23.0  29.0
       White                8642.0  36.811618  14.329093  17.0  25.0  35.0
Male   Amer-Indian-Eskimo    192.0  37.208333  12.049563  17.0  28.0  35.0
       Asian-Pac-Islander    693.0  39.073593  12.883944  18.0  29.0  37.0
       Black                1569.0  37.682600  12.882612  17.0  27.0  36.0
       Other                 162.0  34.654321  11.355531  17.0  26.0  32.0
       White               19174.0  39.652498  13.436029  17.0  29.0  38.0

                             75%   max
sex    race
Female Amer-Indian-Eskimo  46.00  80.0
       Asian-Pac-Islander  43.75  75.0
       Black               46.00  90.0
       Other               39.00  74.0
       White               46.00  90.0
Male   Amer-Indian-Eskimo  45.00  82.0
       Asian-Pac-Islander  46.00  90.0
       Black               46.00  90.0
       Other               42.00  77.0
       White               49.00  90.0

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [56]:
data[data['salary']=='>50K']['marital-status'].value_counts()

Married-civ-spouse       6692
Never-married             491
Divorced                  463
Widowed                    85
Separated                  66
Married-spouse-absent      34
Married-AF-spouse          10
Name: marital-status, dtype: int64

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [141]:
#pd.crosstab(data['hours-per-week'], data['salary'])
data[data['hours-per-week']==data['hours-per-week'].max()]['sex'].count()

85

In [140]:
#pd.crosstab(data['hours-per-week'], data['salary'])
data.groupby(['hours-per-week'])['salary'].value_counts(normalize=True)

hours-per-week  salary
1               <=50K     0.900000
                >50K      0.100000
2               <=50K     0.750000
                >50K      0.250000
3               <=50K     0.974359
                >50K      0.025641
4               <=50K     0.944444
                >50K      0.055556
5               <=50K     0.883333
                >50K      0.116667
6               <=50K     0.875000
                >50K      0.125000
7               <=50K     0.846154
                >50K      0.153846
8               <=50K     0.924138
                >50K      0.075862
9               <=50K     0.944444
                >50K      0.055556
10              <=50K     0.928058
                >50K      0.071942
11              <=50K     1.000000
12              <=50K     0.930636
                >50K      0.069364
13              <=50K     0.913043
                >50K      0.086957
14              <=50K     0.941176
                >50K      0.058824
15              <=50K     0.962871
                >50K      0.037129
16              <=50K     0.936585
                            ...
78              <=50K     0.750000
                >50K      0.250000
80              <=50K     0.571429
                >50K      0.428571
81              <=50K     1.000000
82              <=50K     1.000000
84              <=50K     0.622222
                >50K      0.377778
85              <=50K     0.692308
                >50K      0.307692
86              <=50K     1.000000
87              <=50K     1.000000
88              <=50K     1.000000
89              <=50K     0.500000
                >50K      0.500000
90              <=50K     0.655172
                >50K      0.344828
91              <=50K     1.000000
92              <=50K     1.000000
94              <=50K     1.000000
95              <=50K     0.500000
                >50K      0.500000
96              <=50K     0.800000
                >50K      0.200000
97              <=50K     0.500000
                >50K      0.500000
98              <=50K     0.727273
                >50K      0.272727
99              <=50K     0.705882
                >50K      0.294118
Name: salary, Length: 173, dtype: float64

In [139]:
pd.crosstab(data['hours-per-week']==data['hours-per-week'].max(), data['salary'])

salary          <=50K  >50K
hours-per-week
False           24660  7816
True               60    25

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [108]:
data.groupby(['salary', 'native-country'])['hours-per-week'].mean()

salary  native-country
<=50K   ?                             40.164760
        Cambodia                      41.416667
        Canada                        37.914634
        China                         37.381818
        Columbia                      38.684211
        Cuba                          37.985714
        Dominican-Republic            42.338235
        Ecuador                       38.041667
        El-Salvador                   36.030928
        England                       40.483333
        France                        41.058824
        Germany                       39.139785
        Greece                        41.809524
        Guatemala                     39.360656
        Haiti                         36.325000
        Holand-Netherlands            40.000000
        Honduras                      34.333333
        Hong                          39.142857
        Hungary                       31.300000
        India                         38.233333
        Iran                          41.440000
        Ireland                       40.947368
        Italy                         39.625000
        Jamaica                       38.239437
        Japan                         41.000000
        Laos                          40.375000
        Mexico                        40.003279
        Nicaragua                     36.093750
        Outlying-US(Guam-USVI-etc)    41.857143
        Peru                          35.068966
                                        ...
>50K    France                        50.750000
        Germany                       44.977273
        Greece                        50.625000
        Guatemala                     36.666667
        Haiti                         42.750000
        Honduras                      60.000000
        Hong                          45.000000
        Hungary                       50.000000
        India                         46.475000
        Iran                          47.500000
        Ireland                       48.000000
        Italy                         45.400000
        Jamaica                       41.100000
        Japan                         47.958333
        Laos                          40.000000
        Mexico                        46.575758
        Nicaragua                     37.500000
        Peru                          40.000000
        Philippines                   43.032787
        Poland                        39.000000
        Portugal                      41.500000
        Puerto-Rico                   39.416667
        Scotland                      46.666667
        South                         51.437500
        Taiwan                        46.800000
        Thailand                      58.333333
        Trinadad&Tobago               40.000000
        United-States                 45.505369
        Vietnam                       39.200000
        Yugoslavia                    49.500000
Name: hours-per-week, Length: 82, dtype: float64